// Generated by scripts/build-client.mjs; edit client/index.mjs instead.
window.__ModuleLoader__.load({
  id: 'dsh-rpm',
  factory: (function createClientPlugin(require) {
  const React = require('react');
  const { createElement: h, useCallback, useEffect, useId, useRef, useState, useSyncExternalStore } = React;
  const SECTION_ID = 'dsh-rpm';
  const LEGACY_NAMESPACE = 'dsh-rpm';
  const ENTRY_ID = 'dsh-rpm';
  const inject = ['slots', 'remote', 'remote.llm'];
  const SAVE_ERROR = 'Could not save this setting. It may have changed elsewhere. Review the current value and try again.';

  function isRecord(value) {
    return value !== null && typeof value === 'object' && !Array.isArray(value);
  }

  function text(value, fallback) {
    return typeof value === 'string' && value.trim() !== '' ? value : fallback;
  }

  /** Settings namespace of this plugin's host entry among the served ones. */
  function findEntryNamespace(namespaces) {
    const ids = (Array.isArray(namespaces) ? namespaces : []).map(view => view?.ns).filter(id => typeof id === 'string');
    return ids.find(id => id === `include:${ENTRY_ID}`)
      ?? ids.find(id => id === ENTRY_ID)
      ?? ids.find(id => id.endsWith(`:${ENTRY_ID}`));
  }

  /**
   * Join the registered providers and the stored limits into display rows.
   * Rate limiting applies to every provider route, so every registered
   * provider is listed. Pure, so tests can call it directly.
   */
  function buildRows({ registered = [], limits = {} }) {
    const rows = new Map();
    for (const provider of Array.isArray(registered) ? registered : []) {
      if (!isRecord(provider) || typeof provider.id !== 'string' || provider.id === '') continue;
      const route = provider.id;
      rows.set(route, { route, name: text(provider.name, route), active: true });
    }
    // A limited provider that no longer exists stays visible so its limit can be removed.
    for (const [route, rpm] of Object.entries(isRecord(limits) ? limits : {})) {
      if (typeof rpm !== 'number' || !(rpm > 0) || rows.has(route)) continue;
      rows.set(route, { route, name: route, active: false });
    }
    return [...rows.values()].sort((a, b) => a.name.localeCompare(b.name, undefined, { sensitivity: 'base' }));
  }

  const styles = {
    page: { display: 'flex', flexDirection: 'column', gap: '16px', maxWidth: '720px', fontSize: '13px', color: 'var(--dsw-alias-label-primary)' },
    title: { margin: 0, fontSize: '18px', lineHeight: '26px', fontWeight: 600 },
    lead: { margin: '4px 0 0', lineHeight: '20px', color: 'var(--dsw-alias-label-secondary)' },
    notice: {
      margin: 0, padding: '10px 12px', border: '1px solid var(--dsw-alias-border-l1)',
      borderInlineStart: '3px solid var(--dsw-alias-state-warn-primary)', borderRadius: '8px',
      fontSize: '12px', lineHeight: '18px', color: 'var(--dsw-alias-label-secondary)', overflowWrap: 'anywhere',
    },
    list: { listStyle: 'none', margin: 0, padding: 0, border: '1px solid var(--dsw-alias-border-l1)', borderRadius: '8px', overflow: 'hidden' },
    row: { display: 'flex', alignItems: 'center', gap: '12px', padding: '10px 12px', borderTop: '1px solid var(--dsw-alias-border-l1)', minWidth: 0 },
    rowFirst: { borderTop: 'none' },
    rowText: { display: 'flex', flexDirection: 'column', gap: '2px', minWidth: 0, flex: 1 },
    rowName: { fontWeight: 500, overflowWrap: 'anywhere' },
    rowMeta: { fontSize: '12px', color: 'var(--dsw-alias-label-secondary)', overflowWrap: 'anywhere' },
    controls: { display: 'flex', alignItems: 'center', gap: '8px', flexShrink: 0 },
    input: {
      width: '110px', padding: '4px 8px', boxSizing: 'border-box',
      border: '1px solid var(--dsw-alias-border-l2)', borderRadius: '6px',
      background: 'transparent', color: 'inherit', font: 'inherit',
    },
    button: {
      alignSelf: 'flex-start', padding: '4px 12px', border: '1px solid var(--dsw-alias-border-l2)', borderRadius: '6px',
      background: 'transparent', color: 'inherit', font: 'inherit', cursor: 'pointer',
    },
    status: { margin: 0, color: 'var(--dsw-alias-label-secondary)' },
    error: { margin: 0, color: 'var(--dsw-alias-state-error-primary)' },
  };

  const emptyMirror = { view: undefined };
  const unavailableSnapshot = { status: 'unavailable', value: undefined, revision: undefined, writable: false, mode: 'host' };
  const noForm = { getSnapshot: () => unavailableSnapshot, subscribe: () => () => {}, mutate: async () => false };

  function useStore(store, fallback) {
    const subscribe = useCallback(listener => (store ? store.subscribe(listener) : () => {}), [store]);
    const getSnapshot = useCallback(() => (store ? store.getSnapshot() : fallback), [store, fallback]);
    return useSyncExternalStore(subscribe, getSnapshot, getSnapshot);
  }

  function rowDetail(row) {
    return row.active ? row.route : `${row.route} · no longer configured. Clear the limit to remove it.`;
  }

  function ProviderRow({ row, first, saved, revision, disabled, onSave }) {
    const id = useId();
    const detailId = useId();
    const [draft, setDraft] = useState('');
    const [dirty, setDirty] = useState(false);
    // Follow every committed change (this save, another tab, a reload):
    // the revision moves even when the value does not (e.g. clearing an unset limit).
    useEffect(() => {
      setDraft('');
      setDirty(false);
    }, [saved, revision, row.route]);
    // Untouched fields track the persisted value; edits stay until saved.
    const display = dirty ? draft : (typeof saved === 'number' ? String(saved) : '');
    return h('li', { style: first ? { ...styles.row, ...styles.rowFirst } : styles.row },
      h('span', { style: styles.rowText },
        h('label', { htmlFor: id, style: styles.rowName }, row.name),
        h('span', { id: detailId, style: styles.rowMeta }, rowDetail(row))),
      h('span', { style: styles.controls },
        h('input', {
          id, type: 'number', min: 0, step: 1, placeholder: 'unlimited',
          value: display, disabled,
          'aria-label': `Requests-per-minute limit for ${row.route}`,
          'aria-describedby': detailId,
          onChange: event => { setDraft(event.currentTarget.value); setDirty(true); },
          style: styles.input,
        }),
        h('button', {
          type: 'button', disabled, style: styles.button,
          onClick: () => onSave(row.route, display),
        }, 'Apply')));
  }

  function RateLimitsSection({ source }) {
    const mirrorSnapshot = useStore(source.describe, emptyMirror);
    const namespaces = mirrorSnapshot?.view?.namespaces ?? [];
    const form = source.formFor(namespaces);
    const snapshot = useStore(form ?? noForm, unavailableSnapshot);
    const [directory, setDirectory] = useState({ status: 'loading', registered: [], error: '' });
    const [pending, setPending] = useState('');
    const [error, setError] = useState('');
    const busy = useRef(false);
    const mounted = useRef(true);
    const generation = useRef(0);

    const load = useCallback(async () => {
      const current = ++generation.current;
      try {
        const registered = await source.listProviders();
        if (!mounted.current || current !== generation.current) return;
        if (!registered?.ok) throw new Error('list failed');
        setDirectory({ status: 'ready', registered: Array.isArray(registered.value) ? registered.value : [], error: '' });
      } catch {
        if (mounted.current && current === generation.current) {
          setDirectory(previous => ({ ...previous, status: 'error', error: 'Could not load the provider list.' }));
        }
      }
    }, [source]);

    useEffect(() => {
      mounted.current = true;
      try { void source.describe?.ensure?.(); } catch { /* the mirror reports its own failure */ }
      void load();
      const off = source.onInvalidate(() => { void load(); });
      return () => { mounted.current = false; off(); };
    }, [source, load]);

    const limits = isRecord(snapshot.value?.providers) ? snapshot.value.providers : {};
    const rows = buildRows({ registered: directory.registered, limits });
    const writable = snapshot.status === 'ready' && snapshot.writable === true && snapshot.mode === 'host';

    async function save(route, display) {
      if (!writable || busy.current || form === undefined) return;
      const trimmed = String(display).trim();
      const next = trimmed === '' ? 0 : Number(trimmed);
      if (!Number.isInteger(next) || next < 0) {
        if (mounted.current) setError('Enter 0 (unlimited) or a positive whole number.');
        return;
      }
      busy.current = true;
      setPending(route);
      setError('');
      try {
        // Fence the rendered revision. A refused write can settle without
        // throwing (0.1.5 recovers and resolves, 0.1.7+ answers false), so the
        // stored value is confirmed instead of trusting settlement.
        await form.mutate([next === 0
          ? { op: 'unset', path: ['providers', route] }
          : { op: 'set', path: ['providers', route], value: next }], snapshot.revision);
        const settled = form.getSnapshot();
        const settledValue = settled.value?.providers?.[route] ?? 0;
        if (settled.status !== 'ready' || settledValue !== next) {
          throw new Error('Setting was not confirmed');
        }
      } catch {
        // Never render raw transport errors: they can carry configuration details.
        if (mounted.current) setError(SAVE_ERROR);
      } finally {
        busy.current = false;
        if (mounted.current) setPending('');
      }
    }

    let status = null;
    if (mirrorSnapshot?.view === undefined && form === undefined) status = 'Loading settings…';
    else if (form === undefined || snapshot.status === 'unavailable') {
      status = 'The dsh-rpm host plugin is not running, so these settings cannot be changed. Check the dsh startup output: the plugin refuses to load on an unsupported DSH version.';
    } else if (snapshot.status === 'loading') status = 'Loading settings…';
    else if (!writable) status = 'These settings are read-only in this browser.';

    const limitedCount = rows.filter(row => typeof limits[row.route] === 'number' && limits[row.route] > 0).length;
    return h('section', { style: styles.page, 'aria-labelledby': `${SECTION_ID}-title` },
      h('header', null,
        h('h2', { id: `${SECTION_ID}-title`, style: styles.title }, 'Rate limits'),
        h('p', { style: styles.lead },
          'Caps how many model requests each provider receives per minute. ',
          'Requests beyond a provider\u2019s limit are delayed until the next one-minute window instead of failing.')),
      h('p', { role: 'note', style: styles.notice },
        'Limits apply to every session immediately, including subagents and retries. Every provider is unlimited by default; enter ',
        h('code', null, '0'), ' or leave the field empty to remove a limit.'),
      status === null ? null : h('p', { role: 'status', style: styles.status }, status),
      directory.status === 'loading' && rows.length === 0 ? h('p', { role: 'status', style: styles.status }, 'Loading providers…') : null,
      directory.status === 'error'
        ? h('div', { style: { display: 'flex', flexDirection: 'column', gap: '8px' } },
          h('p', { role: 'alert', style: styles.error }, directory.error),
          h('button', { type: 'button', style: styles.button, onClick: () => { void load(); } }, 'Retry'))
        : null,
      directory.status === 'ready' && rows.length === 0
        ? h('p', { style: styles.status }, 'No model providers are configured yet. Add one in Settings → Models.')
        : null,
      rows.length > 0
        ? h('div', { style: { display: 'flex', flexDirection: 'column', gap: '6px' } },
          h('p', { style: styles.status }, `Providers (${limitedCount} limited)`),
          h('ul', { style: styles.list, 'aria-label': 'Providers' },
            rows.map((row, index) => h(ProviderRow, {
              key: row.route, row, first: index === 0,
              saved: limits[row.route],
              revision: snapshot.revision,
              disabled: !writable || pending !== '',
              onSave: (route, display) => { void save(route, display); },
            }))))
        : null,
      pending !== '' ? h('p', { role: 'status', style: styles.status }, 'Saving…') : null,
      error !== '' ? h('p', { role: 'alert', style: styles.error }, error) : null);
  }

  function registerSection(ctx, source) {
    ctx.slots.inject('settings.section', () => ctx.slots.register({
      name: 'settings.section',
      id: SECTION_ID,
      order: 61,
      label: () => 'Rate limits',
      inject: () => ({ source }),
    }, RateLimitsSection));
  }

  function remoteSource(ctx) {
    return {
      listProviders: () => ctx.remote.llm.listProviders(),
      onInvalidate(listener) {
        if (typeof ctx.remote.$on !== 'function') return () => {};
        const offs = ['llm/adapters-updated', 'settings/document-updated'].map(event => {
          try { return ctx.remote.$on(event, listener); } catch { return undefined; }
        }).filter(off => typeof off === 'function');
        return () => { for (const off of offs) off(); };
      },
    };
  }

  function apply(ctx) {
    const remote = remoteSource(ctx);
    // DSH 0.1.7 and later: the settings are this plugin entry's Config.
    ctx.inject(['configForms'], child => {
      const forms = child.configForms;
      let cached;
      registerSection(child, {
        ...remote,
        describe: forms.describe(),
        formFor(namespaces) {
          const ns = findEntryNamespace(namespaces);
          if (ns === undefined) return undefined;
          if (cached?.ns !== ns) cached = { ns, form: forms.get(ns) };
          return cached.form;
        },
      });
    });
    // DSH 0.1.5: the per-namespace settingsScope service.
    ctx.inject(['settingsScope'], child => {
      // bind() belongs to this calling fiber; it owns subscription/write teardown.
      const scope = child.settingsScope.bind({ namespace: LEGACY_NAMESPACE });
      registerSection(child, {
        ...remote,
        describe: child.settingsScope.describe(),
        formFor: () => scope,
      });
    });
  }

  return { inject, apply, buildRows, findEntryNamespace };
})
});
